### ISSUE TITLE
unrar being added upstream

### ISSUE THREAD

**Issue by nomandera** [linuxserver/docker-sickgear#11]
Follow discussions https://github.com/SickGear/SickGear.Docker/pull/31 and implement a suitable lsio ecosytem alternative when upstream decision made.

**Comment by thelamer** [comment]
We allready have unrar in our container https://github.com/linuxserver/docker-baseimage-alpine-python/blob/master/Dockerfile#L39

**Comment by nomandera** [comment]
Prematurely closed as they were discussing pinning to edge but coincidentally ok as they didnt.

**Comment by thelamer** [comment]
I don't follow , this package is in our python baseimage so regardless of any decision made by a third party we would not be changing that. 

Is there something I am missing here ?
